package defpackage;

import org.codeaurora.snapcam.R;

/* renamed from: alx  reason: default package */
/* loaded from: classes.dex */
public final class alx {
    public static final int[] a = {16843033, R.attr.background_border_cap, R.attr.background_border_color, R.attr.background_border_width, R.attr.background_color, R.attr.background_radius, R.attr.background_radius_percent, R.attr.background_radius_pressed, R.attr.background_radius_pressed_percent, R.attr.background_shadow_width, R.attr.circle_border_cap, R.attr.circle_border_color, R.attr.circle_border_width, R.attr.circle_color, R.attr.circle_padding, R.attr.circle_radius, R.attr.circle_radius_percent, R.attr.circle_radius_pressed, R.attr.circle_radius_pressed_percent, R.attr.clip_dimen, R.attr.image_circle_percentage, R.attr.image_horizontal_offcenter_percentage, R.attr.image_tint, R.attr.img_circle_percentage, R.attr.img_horizontal_offset_percentage, R.attr.img_padding, R.attr.img_tint, R.attr.shadow_width, R.attr.square_dimen};
    public static final int[] b = {R.attr.pageIndicatorDotColor, R.attr.pageIndicatorDotColorSelected, R.attr.pageIndicatorDotFadeInDuration, R.attr.pageIndicatorDotFadeOutDelay, R.attr.pageIndicatorDotFadeOutDuration, R.attr.pageIndicatorDotFadeWhenIdle, R.attr.pageIndicatorDotRadius, R.attr.pageIndicatorDotRadiusSelected, R.attr.pageIndicatorDotShadowColor, R.attr.pageIndicatorDotShadowDx, R.attr.pageIndicatorDotShadowDy, R.attr.pageIndicatorDotShadowRadius, R.attr.pageIndicatorDotSpacing, R.attr.wsPageIndicatorDotColor, R.attr.wsPageIndicatorDotColorSelected, R.attr.wsPageIndicatorDotFadeInDuration, R.attr.wsPageIndicatorDotFadeOutDelay, R.attr.wsPageIndicatorDotFadeOutDuration, R.attr.wsPageIndicatorDotFadeWhenIdle, R.attr.wsPageIndicatorDotRadius, R.attr.wsPageIndicatorDotRadiusSelected, R.attr.wsPageIndicatorDotShadowColor, R.attr.wsPageIndicatorDotShadowDx, R.attr.wsPageIndicatorDotShadowDy, R.attr.wsPageIndicatorDotShadowRadius, R.attr.wsPageIndicatorDotSpacing};
}
