package defpackage;

import android.content.ContentResolver;
import android.content.Context;
import android.content.Intent;
import android.content.res.Resources;
import android.os.Handler;
import android.view.Window;

import com.google.android.apps.camera.bottombar.BottomBarController;
import com.google.android.apps.camera.stats.timing.CameraActivityTiming;

import java.util.concurrent.Executor;

/* renamed from: eus  reason: default package */
/* loaded from: classes.dex */
public final class eus implements pys {
    private final qkg A;
    private final qkg B;
    private final qkg C;
    private final qkg D;
    private final qkg E;
    private final qkg F;
    private final qkg G;
    private final qkg H;
    private final qkg I;
    private final qkg J;
    private final qkg K;
    private final qkg L;
    private final qkg M;
    private final qkg N;
    private final qkg O;
    private final qkg P;
    private final qkg Q;
    private final qkg R;
    private final qkg S;
    private final qkg T;
    private final qkg U;
    private final qkg V;
    private final qkg W;
    private final qkg X;
    private final qkg Y;
    private final qkg Z;
    private final qkg a;
    private final qkg aa;
    private final qkg ab;
    private final qkg ac;
    private final qkg ad;
    private final qkg ae;
    private final qkg af;
    private final qkg ag;
    private final qkg ah;
    private final qkg ai;
    private final qkg aj;
    private final qkg ak;
    private final qkg al;
    private final qkg am;
    private final qkg an;
    private final qkg ao;
    private final qkg ap;
    private final qkg aq;
    private final qkg ar;
    private final qkg as;
    private final qkg at;
    private final qkg au;
    private final qkg b;
    private final qkg c;
    private final qkg d;
    private final qkg e;
    private final qkg f;
    private final qkg g;
    private final qkg h;
    private final qkg i;
    private final qkg j;
    private final qkg k;
    private final qkg l;
    private final qkg m;
    private final qkg n;
    private final qkg o;
    private final qkg p;
    private final qkg q;
    private final qkg r;
    private final qkg s;
    private final qkg t;
    private final qkg u;
    private final qkg v;
    private final qkg w;
    private final qkg x;
    private final qkg y;
    private final qkg z;

    public eus(qkg qkgVar, qkg qkgVar2, qkg qkgVar3, qkg qkgVar4, qkg qkgVar5, qkg qkgVar6, qkg qkgVar7, qkg qkgVar8, qkg qkgVar9, qkg qkgVar10, qkg qkgVar11, qkg qkgVar12, qkg qkgVar13, qkg qkgVar14, qkg qkgVar15, qkg qkgVar16, qkg qkgVar17, qkg qkgVar18, qkg qkgVar19, qkg qkgVar20, qkg qkgVar21, qkg qkgVar22, qkg qkgVar23, qkg qkgVar24, qkg qkgVar25, qkg qkgVar26, qkg qkgVar27, qkg qkgVar28, qkg qkgVar29, qkg qkgVar30, qkg qkgVar31, qkg qkgVar32, qkg qkgVar33, qkg qkgVar34, qkg qkgVar35, qkg qkgVar36, qkg qkgVar37, qkg qkgVar38, qkg qkgVar39, qkg qkgVar40, qkg qkgVar41, qkg qkgVar42, qkg qkgVar43, qkg qkgVar44, qkg qkgVar45, qkg qkgVar46, qkg qkgVar47, qkg qkgVar48, qkg qkgVar49, qkg qkgVar50, qkg qkgVar51, qkg qkgVar52, qkg qkgVar53, qkg qkgVar54, qkg qkgVar55, qkg qkgVar56, qkg qkgVar57, qkg qkgVar58, qkg qkgVar59, qkg qkgVar60, qkg qkgVar61, qkg qkgVar62, qkg qkgVar63, qkg qkgVar64, qkg qkgVar65, qkg qkgVar66, qkg qkgVar67, qkg qkgVar68, qkg qkgVar69, qkg qkgVar70, qkg qkgVar71, qkg qkgVar72, qkg qkgVar73) {
        this.a = qkgVar;
        this.b = qkgVar2;
        this.c = qkgVar3;
        this.d = qkgVar4;
        this.e = qkgVar5;
        this.f = qkgVar6;
        this.g = qkgVar7;
        this.h = qkgVar8;
        this.i = qkgVar9;
        this.j = qkgVar10;
        this.k = qkgVar11;
        this.l = qkgVar12;
        this.m = qkgVar13;
        this.n = qkgVar14;
        this.o = qkgVar15;
        this.p = qkgVar16;
        this.q = qkgVar17;
        this.r = qkgVar18;
        this.s = qkgVar19;
        this.t = qkgVar20;
        this.u = qkgVar21;
        this.v = qkgVar22;
        this.w = qkgVar23;
        this.x = qkgVar24;
        this.y = qkgVar25;
        this.z = qkgVar26;
        this.A = qkgVar27;
        this.B = qkgVar28;
        this.C = qkgVar29;
        this.D = qkgVar30;
        this.E = qkgVar31;
        this.F = qkgVar32;
        this.G = qkgVar33;
        this.H = qkgVar34;
        this.I = qkgVar35;
        this.J = qkgVar36;
        this.K = qkgVar37;
        this.L = qkgVar38;
        this.M = qkgVar39;
        this.N = qkgVar40;
        this.O = qkgVar41;
        this.P = qkgVar42;
        this.Q = qkgVar43;
        this.R = qkgVar44;
        this.S = qkgVar45;
        this.T = qkgVar46;
        this.U = qkgVar47;
        this.V = qkgVar48;
        this.W = qkgVar49;
        this.X = qkgVar50;
        this.Y = qkgVar51;
        this.Z = qkgVar52;
        this.aa = qkgVar53;
        this.ab = qkgVar54;
        this.ac = qkgVar55;
        this.ad = qkgVar56;
        this.ae = qkgVar57;
        this.af = qkgVar58;
        this.ag = qkgVar59;
        this.ah = qkgVar60;
        this.ai = qkgVar61;
        this.aj = qkgVar62;
        this.ak = qkgVar63;
        this.al = qkgVar64;
        this.am = qkgVar65;
        this.an = qkgVar66;
        this.ao = qkgVar67;
        this.ap = qkgVar68;
        this.aq = qkgVar69;
        this.ar = qkgVar70;
        this.as = qkgVar71;
        this.at = qkgVar72;
        this.au = qkgVar73;
    }

    @Override // defpackage.qkg
    /* renamed from: get */
    public final /* synthetic */ Object mo37get() {
        Context a = ((emp) this.a).a();
        Context mo37get = ((emd) this.b).mo37get();
        Resources mo37get2 = ((emf) this.c).mo37get();
        Window mo37get3 = ((emg) this.d).mo37get();
        ContentResolver mo37get4 = ((emc) this.e).mo37get();
        Handler b = efb.b();
        emb mo37get5 = ((eth) this.f).mo37get();
        ((jnx) this.g).mo37get();
        fhv mo37get6 = ((etj) this.h).mo37get();
        ih mo37get7 = ((emi) this.i).mo37get();
        bqg mo37get8 = ((etg) this.j).mo37get();
        brc brcVar = (brc) this.k.mo37get();
        lar larVar = (lar) this.l.mo37get();
        Executor executor = (Executor) this.m.mo37get();
        fxi fxiVar = (fxi) this.n.mo37get();
        boolean booleanValue = ((Boolean) this.o.mo37get()).booleanValue();
        gvb gvbVar = (gvb) this.p.mo37get();
        lwf lwfVar = (lwf) this.q.mo37get();
        pht phtVar = (pht) this.r.mo37get();
        lkd lkdVar = (lkd) this.s.mo37get();
        fix fixVar = (fix) this.t.mo37get();
        hub hubVar = (hub) this.u.mo37get();
        huf hufVar = (huf) this.v.mo37get();
        hug hugVar = (hug) this.w.mo37get();
        ((huh) this.x).mo37get();
        jcf jcfVar = (jcf) this.y.mo37get();
        jng jngVar = (jng) this.z.mo37get();
        jns mo37get9 = ((jnw) this.A).mo37get();
        pyn a2 = pyr.a(this.B);
        hvb hvbVar = (hvb) this.C.mo37get();
        dlt dltVar = (dlt) this.D.mo37get();
        hnx hnxVar = (hnx) this.E.mo37get();
        qkg qkgVar = this.F;
        khx khxVar = (khx) this.G.mo37get();
        ljf ljfVar = (ljf) this.H.mo37get();
        ijn ijnVar = (ijn) this.I.mo37get();
        CameraActivityTiming cameraActivityTiming = (CameraActivityTiming) this.J.mo37get();
        qkg qkgVar2 = this.K;
        ixj ixjVar = (ixj) this.L.mo37get();
        ixx ixxVar = (ixx) this.M.mo37get();
        fch fchVar = (fch) this.N.mo37get();
        jqo mo37get10 = ((jqp) this.O).mo37get();
        Intent mo37get11 = ((emj) this.P).mo37get();
        BottomBarController bottomBarController = (BottomBarController) this.Q.mo37get();
        ddf ddfVar = (ddf) this.R.mo37get();
        epj epjVar = (epj) this.S.mo37get();
        fjs fjsVar = (fjs) this.T.mo37get();
        ojc ojcVar = (ojc) ((pyt) this.U).a;
        jfn jfnVar = (jfn) this.V.mo37get();
        gtg gtgVar = (gtg) this.W.mo37get();
        lda ldaVar = (lda) this.X.mo37get();
        lda ldaVar2 = (lda) this.Y.mo37get();
        lda ldaVar3 = (lda) this.Z.mo37get();
        lda ldaVar4 = (lda) this.aa.mo37get();
        qkg qkgVar3 = this.ab;
        hrx hrxVar = (hrx) this.ac.mo37get();
        pyn a3 = pyr.a(this.ad);
        cvo cvoVar = (cvo) this.ae.mo37get();
        kas mo37get12 = ((iwi) this.af).mo37get();
        jdk jdkVar = (jdk) this.ag.mo37get();
        lco lcoVar = (lco) this.ah.mo37get();
        lda ldaVar5 = (lda) this.ai.mo37get();
        ojc a4 = ((hlj) this.aj).a();
        pyn a5 = pyr.a(this.ak);
        pyn a6 = pyr.a(this.al);
        hvg mo37get13 = ((hvh) this.am).mo37get();
        pih pihVar = (pih) this.an.mo37get();
        lda ldaVar6 = (lda) this.ao.mo37get();
        jsc jscVar = (jsc) this.ap.mo37get();
        hgx hgxVar = (hgx) this.aq.mo37get();
        return new eur(a, mo37get, mo37get2, mo37get3, mo37get4, b, mo37get5, mo37get6, mo37get7, mo37get8, brcVar, larVar, executor, fxiVar, booleanValue, gvbVar, lwfVar, phtVar, lkdVar, fixVar, hubVar, hufVar, hugVar, jcfVar, jngVar, mo37get9, a2, hvbVar, dltVar, hnxVar, qkgVar, khxVar, ljfVar, ijnVar, cameraActivityTiming, qkgVar2, ixjVar, ixxVar, fchVar, mo37get10, mo37get11, bottomBarController, ddfVar, epjVar, fjsVar, jfnVar, gtgVar, ldaVar, ldaVar2, ldaVar3, ldaVar4, qkgVar3, hrxVar, a3, cvoVar, mo37get12, jdkVar, lcoVar, ldaVar5, a4, a5, a6, mo37get13, pihVar, ldaVar6, jscVar, (ojc) this.ar.mo37get(), (imf) this.as.mo37get(), (ojc) this.at.mo37get(), (dqa) this.au.mo37get(), null, null, null, null);
    }
}
