package defpackage;

import java.util.List;
import java.util.concurrent.Executor;

/* renamed from: evo  reason: default package */
/* loaded from: classes.dex */
public final class evo implements cot {
    private final qkg A;
    private final qkg B;
    private final qkg C;
    private final qkg D;
    private final qkg E;
    private final qkg F;
    private final qkg G;
    private final qkg H;
    private final qkg I;
    private final qkg J;
    private final qkg K;
    private final qkg L;
    private final qkg M;
    private final qkg N;
    private final qkg O;
    private final qkg P;
    private final qkg Q;
    private final qkg R;
    private final qkg S;
    private final qkg T;
    private final qkg U;
    private final qkg V;
    private final qkg W;
    private final qkg X;
    private final qkg Y;
    private final qkg Z;
    private final cou a;
    private final qkg aa;
    private final qkg ab;
    private final qkg ac;
    private final qkg ad;
    private final qkg ae;
    private final qkg af;
    private final qkg ag;
    private final ewb b;
    private final qkg c;
    private final qkg d;
    private final qkg e;
    private final qkg f;
    private final qkg g;
    private final qkg h;
    private final qkg i;
    private final qkg j;
    private final qkg k;
    private final qkg l;
    private final qkg m;
    private final qkg n;
    private final qkg o;
    private final qkg p;
    private final qkg q;
    private final qkg r;
    private final qkg s;
    private final qkg t;
    private final qkg u;
    private final qkg v;
    private final qkg w;
    private final qkg x;
    private final qkg y;
    private final qkg z;

    public evo(ewb ewbVar, comClass comClassVar, cou couVar) {
        this.b = ewbVar;
        this.a = couVar;
        pyr.b(coz.a);
        pys pysVar = pyw.a;
        List ah = qmd.ah(1);
        List ah2 = qmd.ah(0);
        qmd.ac(ewbVar.aW, ah);
        pyw aa = qmd.aa(ah, ah2);
        this.c = aa;
        qkg b = pyr.b(dhv.f(ewbVar.aV, aa));
        this.d = b;
        qkg b2 = pyr.b(gnj.a);
        this.e = b2;
        this.f = pyr.b(gcc.i(ewbVar.N, b2));
        cop copVar = new cop(comClassVar);
        this.g = copVar;
        con conVar = new con(comClassVar);
        this.h = conVar;
        qkg b3 = pyr.b(conVar);
        this.i = b3;
        qkg b4 = pyr.b(dhv.e(copVar, b3));
        this.j = b4;
        dhv h = dhv.h(ewbVar.i, b);
        this.k = h;
        qkg b5 = pyr.b(gnc.a);
        this.l = b5;
        gih s = gih.s(b5);
        this.m = s;
        cow cowVar = new cow(couVar, ewbVar.ac, ewbVar.i);
        this.n = cowVar;
        qkg b6 = pyr.b(dvd.h(cowVar, ewbVar.i));
        this.o = b6;
        csn csnVar = new csn(copVar);
        this.p = csnVar;
        coo cooVar = new coo(comClassVar);
        this.q = cooVar;
        cso csoVar = new cso(copVar, csnVar, cooVar, 0);
        this.r = csoVar;
        qkg b7 = pyr.b(dvd.g(b6, csoVar));
        this.s = b7;
        dsd d = dsd.d(b7);
        this.t = d;
        List ah3 = qmd.ah(1);
        List ah4 = qmd.ah(2);
        qmd.ab(h, ah4);
        qmd.ac(s, ah3);
        qmd.ab(d, ah4);
        pyw aa2 = qmd.aa(ah3, ah4);
        this.u = aa2;
        qkg b8 = pyr.b(gcc.j(aa2, ewbVar.aX));
        this.v = b8;
        qkg b9 = pyr.b(dhx.a(b8));
        this.w = b9;
        qkg b10 = pyr.b(dhv.d(copVar, b4));
        this.x = b10;
        qkg b11 = pyr.b(dpd.c(copVar, b10, b8));
        this.y = b11;
        List ah5 = qmd.ah(11);
        List ah6 = qmd.ah(0);
        qmd.ac(ewbVar.aY, ah5);
        qmd.ac(ewbVar.aZ, ah5);
        qmd.ac(ewbVar.ba, ah5);
        qmd.ac(ewbVar.bb, ah5);
        qmd.ac(ewbVar.bc, ah5);
        qmd.ac(ewbVar.bd, ah5);
        qmd.ac(ewbVar.be, ah5);
        qmd.ac(ewbVar.bh, ah5);
        qmd.ac(ewbVar.bl, ah5);
        qmd.ac(ewbVar.bp, ah5);
        qmd.ac(ewbVar.bs, ah5);
        pyw aa3 = qmd.aa(ah5, ah6);
        this.z = aa3;
        qkg b12 = pyr.b(dlf.b(b9, b11, b4, aa3));
        this.A = b12;
        brh b13 = brh.b(ewbVar.bm, ewbVar.bn, cowVar, ewbVar.i);
        this.B = b13;
        cax d2 = cax.d(ewbVar.i, b4, b12, cowVar, b13, b5, ewbVar.k);
        this.C = d2;
        qkg b14 = pyr.b(gni.a);
        this.D = b14;
        qkg b15 = pyr.b(gcc.h(ewbVar.N, b14));
        this.E = b15;
        qkg b16 = pyr.b(new bqq(ewbVar.g, (qkg) cowVar, ewbVar.i, b15, ewbVar.k, ewbVar.bt, 10, (int[][]) null));
        this.F = b16;
        this.G = pyr.b(dvd.d(ewbVar.bg, b8));
        qkg b17 = pyr.b(dvd.f(ewbVar.bg, ewbVar.i));
        this.H = b17;
        qkg b18 = pyr.b(dpd.f(ewbVar.bu, csnVar, cowVar));
        this.I = b18;
        qkg b19 = pyr.b(jhe.a(ewbVar.ab, cowVar, ewbVar.i));
        this.J = b19;
        qkg b20 = pyr.b(bqq.d(ewbVar.i, cowVar, b19, ewbVar.bu, b7, csoVar));
        this.K = b20;
        qkg b21 = pyr.b(new cso(b17, b18, b20, 1));
        this.L = b21;
        fub b22 = fub.b(b21);
        this.M = b22;
        qkg b23 = pyr.b(hjt.a(b22));
        this.N = b23;
        qkg b24 = pyr.b(hlf.a);
        this.O = b24;
        qkg b25 = pyr.b(hkl.a);
        this.P = b25;
        hkf b26 = hkf.b(ewbVar.bv, ewbVar.bw, ewbVar.bx, ewbVar.by);
        this.Q = b26;
        qkg c = evv.c(ewbVar.bo);
        this.R = c;
        qkg b27 = pyr.b(hkj.a(b16, b23, b24, b25, b26, ewbVar.bk, c, csl.a, ewbVar.bv, ewbVar.bz, ewbVar.bA, b8));
        this.S = b27;
        qkg b28 = pyr.b(new cax((qkg) copVar, (qkg) b13, (qkg) conVar, b27, ewbVar.bB, b19, b8, 4, (int[]) null));
        this.T = b28;
        boe boeVar = new boe((qkg) cooVar, b28, ewbVar.bD, b8, 15, (short[][][]) null);
        this.U = boeVar;
        ciu ciuVar = new ciu(cooVar, 8);
        this.V = ciuVar;
        qkg b29 = pyr.b(esp.f(b21, ciuVar));
        this.W = b29;
        cbh cbhVar = new cbh(b8, b29, 10, (int[]) null);
        this.X = cbhVar;
        cbh cbhVar2 = new cbh(cooVar, ewbVar.bC, 11, (boolean[]) null);
        this.Y = cbhVar2;
        List ah7 = qmd.ah(3);
        List ah8 = qmd.ah(1);
        qmd.ab(d2, ah8);
        qmd.ac(boeVar, ah7);
        qmd.ac(cbhVar, ah7);
        qmd.ac(cbhVar2, ah7);
        this.Z = qmd.aa(ah7, ah8);
        dsd c2 = dsd.c(b7);
        this.aa = c2;
        List ah9 = qmd.ah(1);
        List ah10 = qmd.ah(0);
        qmd.ac(c2, ah9);
        pyw aa4 = qmd.aa(ah9, ah10);
        this.ab = aa4;
        qkg b30 = pyr.b(dlf.g(b6, ewbVar.bE, aa4, pyw.a));
        this.ac = b30;
        dvd e = dvd.e(b6, b30);
        this.ad = e;
        List ah11 = qmd.ah(0);
        List ah12 = qmd.ah(1);
        qmd.ab(e, ah12);
        pyw aa5 = qmd.aa(ah11, ah12);
        this.ae = aa5;
        coq coqVar = new coq(comClassVar);
        this.af = coqVar;
        this.ag = pyr.b(gqr.l(aa5, coqVar));
    }

    @Override // defpackage.cot
    public final cos a() {
        nvb nvbVar = this.a.b;
        qmd.ae(nvbVar);
        ohh.U(4, "expectedSize");
        opc opcVar = new opc(null);
        opcVar.i(dhv.a((ddf) this.b.i.mo37get(), this.d));
        opcVar.d(fci.a((Executor) this.b.N.mo37get(), (Executor) this.f.mo37get(), this.Z, pyw.a));
        opcVar.d(fsy.b((lap) this.v.mo37get(), (pht) this.D.mo37get(), (bxj) this.b.G.mo37get()));
        opcVar.d((bvv) this.ag.mo37get());
        return new cos(nvbVar, new gmy(opcVar.f(), (pih) this.e.mo37get(), (Executor) this.E.mo37get(), (ljf) this.b.k.mo37get()), (lap) this.v.mo37get(), (pih) this.D.mo37get(), (lbu) this.b.aX.mo37get(), null, null);
    }
}
