package defpackage;

import org.codeaurora.snapcam.R;

/* renamed from: sf  reason: default package */
/* loaded from: classes2.dex */
public final class sf {
    public static final int[] a = {16842902, 16842903, 16842904, 16842927, 16843087, 16843091, 16843287, 16843288, 16843692, R.attr.maxTextSize, R.attr.minTextSize};
    public static final int[] b = {16842902, 16842903, 16842904, 16842927, 16843033, 16843087, 16843091, 16843173, 16843287, 16843288, 16843692, 16843840, 16843848, R.attr.buttonRippleColor, R.attr.imageScaleMode, R.attr.maxTextSize, R.attr.minTextSize, R.attr.pressedButtonTranslationZ};
    public static final int[] c = {16843033, R.attr.background_border_cap, R.attr.background_border_color, R.attr.background_border_width, R.attr.background_color, R.attr.background_radius, R.attr.background_radius_percent, R.attr.background_radius_pressed, R.attr.background_radius_pressed_percent, R.attr.background_shadow_width, R.attr.circle_border_cap, R.attr.circle_border_color, R.attr.circle_border_width, R.attr.circle_color, R.attr.circle_padding, R.attr.circle_radius, R.attr.circle_radius_percent, R.attr.circle_radius_pressed, R.attr.circle_radius_pressed_percent, R.attr.clip_dimen, R.attr.image_circle_percentage, R.attr.image_horizontal_offcenter_percentage, R.attr.image_tint, R.attr.img_circle_percentage, R.attr.img_horizontal_offset_percentage, R.attr.img_padding, R.attr.img_tint, R.attr.shadow_width, R.attr.square_dimen};
    public static final int[] d = {16842981, 16843033, 16843173, 16843840, 16843848, R.attr.buttonRippleColor, R.attr.imageScaleMode, R.attr.pressedButtonTranslationZ};
    public static final int[] e = {R.attr.backgroundColor, R.attr.backgroundDrawable, R.attr.borderColor, R.attr.borderDashGap, R.attr.borderDashWidth, R.attr.borderRadius, R.attr.borderStyle, R.attr.borderWidth, R.attr.highlightColor, R.attr.iconColor, R.attr.rangedValuePrimaryColor, R.attr.rangedValueProgressHidden, R.attr.rangedValueRingWidth, R.attr.rangedValueSecondaryColor, R.attr.textColor, R.attr.textSize, R.attr.textTypeface, R.attr.titleColor, R.attr.titleSize, R.attr.titleTypeface};
    public static final int[] f = {R.attr.pageIndicatorDotColor, R.attr.pageIndicatorDotColorSelected, R.attr.pageIndicatorDotFadeInDuration, R.attr.pageIndicatorDotFadeOutDelay, R.attr.pageIndicatorDotFadeOutDuration, R.attr.pageIndicatorDotFadeWhenIdle, R.attr.pageIndicatorDotRadius, R.attr.pageIndicatorDotRadiusSelected, R.attr.pageIndicatorDotShadowColor, R.attr.pageIndicatorDotShadowDx, R.attr.pageIndicatorDotShadowDy, R.attr.pageIndicatorDotShadowRadius, R.attr.pageIndicatorDotSpacing, R.attr.wsPageIndicatorDotColor, R.attr.wsPageIndicatorDotColorSelected, R.attr.wsPageIndicatorDotFadeInDuration, R.attr.wsPageIndicatorDotFadeOutDelay, R.attr.wsPageIndicatorDotFadeOutDuration, R.attr.wsPageIndicatorDotFadeWhenIdle, R.attr.wsPageIndicatorDotRadius, R.attr.wsPageIndicatorDotRadiusSelected, R.attr.wsPageIndicatorDotShadowColor, R.attr.wsPageIndicatorDotShadowDx, R.attr.wsPageIndicatorDotShadowDy, R.attr.wsPageIndicatorDotShadowRadius, R.attr.wsPageIndicatorDotSpacing};
}
